### ISSUE TITLE
Script Issue

### ISSUE THREAD

**Issue by jslcom** [GullCode/compile-flash-mayhem#1]
Script runs pretty well, but needs Python2 and does not install it.

**Comment by gullradriel** [comment]
AFAIK It's installing and using python3, even replacing env python call by env python3.
What is the related error you had ?

**Comment by jslcom** [comment]
My apologies for not saving it, but I can produce it again if you like.  Python3 was installed, but some element of the process needed Python2 and errored out.  I installed Python2 and re-ran with success.

Thanks for the awesome script BTW.  I spent about two hours flailing with the Docker build environment before I gave up and spun up a fresh Ubuntu VM and ran your script.  (I am not a novice to Docker either.)  I was actually pretty surprised that I only got one error from your script!

Jeffrey Laing
310-569-6974
