### ISSUE TITLE
Ompiler error using script

### ISSUE THREAD

**Issue by loewal** [GullCode/compile-flash-mayhem#3]
Hi,
The script gives this error:
In file included from /opt/portapack-mayhem/firmware/baseband/sd_over_usb/scsi.c:23:
/opt/portapack-mayhem/firmware/baseband/sd_over_usb/scsi.h:32:10: fatal error: libopencm3/lpc43xx/m4/nvic.h: No such file or directory
   32 | #include <libopencm3/lpc43xx/m4/nvic.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

Before that I tried the manual instructions. Same result.

Please help?

**Comment by loewal** [comment]
tried on 3 different machines...all the same error

**Comment by gullradriel** [comment]
You have to use git clone correctly, you obviously didn't clone the submodules like mentioned in the wiki:
git clone --recurse-submodules https://github.com/eried/portapack-mayhem.git

**Comment by loewal** [comment]
I am sorry @gullradriel,

How can I NOT clone correctly, when I am using your script?

Regards

**Comment by loewal** [comment]
It’s not your script of course. Sorry, Eried’s?

**Comment by gullradriel** [comment]
It's my script. But it's only here so people have an idea of how to set up their env.
And I confirm after tests that you didn't use the git clone --recurse-submodules https://github.com/eried/portapack-mayhem.git .
Or you're trying to build on another copy of the repo.
