### ISSUE TITLE
Cmake error

### ISSUE THREAD

**Issue by Naster17** [GullCode/compile-flash-mayhem#4]
CMake Error at hackrf-portapack/CMakeLists.txt:26 (include):
  include could not find requested file:

    ../hackrf/firmware/hackrf-common.cmake

CMake Error at hackrf-portapack/CMakeLists.txt:30 (add_custom_command):
  add_custom_command Wrong syntax.  A TARGET or OUTPUT must be specified.

CMake Error at hackrf-portapack/CMakeLists.txt:93 (DeclareTargets):
  Unknown CMake command "DeclareTargets".

**Comment by gullradriel** [comment]
That's a problem on your environnement / the way you used the script parts.
From the look of it you just did a git clone and not a git clone --recurse-submodules
